SUSE/caps-automation

harbor-helm/templates/core/core-dpl.yaml, harbor-helm/templates/jobservice/jobservice-dpl.yaml, harbor-helm/templates/registry/registry-dpl.yaml, harbor-helm/values.yaml
Makes some changes that are aligned with the overall strategy of
setting user permissions in the SUSE registry images [1]:
- remove the podSecurityContext entries and use dynamically generated
UIDs instead. The file/folder ownership for mounted volumes that the
containerized process needs write access to is changed by the entrypoint
- use a default docker-registry data volume mount path that corresponds to the
RPM
[1] https://confluence.suse.com/display/ENGCTNRSTORY/Building+Container+Images+and+Helm+Charts#BuildingContainerImagesandHelmCharts-Fileownership
=> Remove hardcoded GIDs from deployments 

harbor-helm/values.yaml
- trivy and notary are marked as optional in TechPreview
=> Disable components not supported in initial release (CAPS-48)

harbor-helm/values.yaml
12.2 is gone, 12.3 should be used by default
=> Bump harbor-db from 12.2 to 12.3

harbor-helm/values.yaml
The new image versioning scheme is meant to support keeping the image
tags unchanged through the entire CI/CD pipeline:
* use tags derived from the Harbor version value for all images
* include the revision number in the tags, to allow us to release
patches independently of upstream
This commit updates the Harbor helm chart with tag values reflecting
the new scheme.
=> Update image tags to match image versioning scheme for Harbor 2.0.0

harbor-helm/templates/trivy/trivy-sts.yaml, harbor-helm/values.yaml
The 1.4.0 helm chart version in the release-2.0 branch could be used
as a baseline for deploying the 2.0.0 SUSE Registry Tech Preview
version using the images in Devel:CAPS:Registry. However, some
trivy related changes crept through and need to be removed (trivy
is not available in the Tech Preview release).
=> Remove trivy helm chart changes from the 2.0 baseline

harbor-helm/Chart.yaml, harbor-helm/README.md, harbor-helm/templates/_helpers.tpl, harbor-helm/templates/chartmuseum/chartmuseum-dpl.yaml, harbor-helm/templates/clair/clair-dpl.yaml, harbor-helm/templates/core/core-cm.yaml, harbor-helm/templates/core/core-dpl.yaml, harbor-helm/templates/core/core-secret.yaml, harbor-helm/templates/database/database-ss.yaml, harbor-helm/templates/internal/auto-tls.yaml, harbor-helm/templates/jobservice/jobservice-dpl.yaml, harbor-helm/templates/nginx/deployment.yaml, harbor-helm/templates/notary/notary-server.yaml, harbor-helm/templates/notary/notary-signer.yaml, harbor-helm/templates/portal/deployment.yaml, harbor-helm/templates/redis/statefulset.yaml, harbor-helm/templates/registry/registry-dpl.yaml, harbor-helm/templates/trivy/trivy-sts.yaml, harbor-helm/values.yaml
Syncs helm chart with upstream v1.4.1 (Harbor 2.0.1) and updates
SUSE helm chart image versions to `2.0.1-rev1`.
Applies all commits from upstream that were done between v1.4.0
(our previous baseline) and v1.4.1.
Images used for the 2.0.1 Private Registry release are uniquely tagged
with `2.0.1-rev1`. They also come from a different IBS project:
`Devel:CAPS:Registry:2.0`.
=> Helm chart update for Private Registry 2.0.1 (CAPS-73)

harbor-helm/templates/database/database-ss.yaml, harbor-helm/values.yaml
If the init container is run with the DB image and explicit runAsUser: 0
security context, it has several advantages:
- no need to need extra image for init container (busybox in this case)
- possibility to run "chown" command with user:group name instead of UID:GID,
which means the whole DB deployment can work with different database images,
without the need to adapt UID:GID values
Signed-off-by: Jiří Suchomel <jiri.suchomel@suse.com>
(cherry picked from commit 15ed669a54aa1561aed59f17ec728b5e8162bd72)
(cherry picked from commit 8be10948b1dbcf8ded9cc293cab110e7ea8296f9)
Corresponding Harbor/master PR: https://github.com/goharbor/harbor-helm/pull/667
=> Run change-permission-of-directory container with DB image

harbor-helm/templates/database/database-ss.yaml, harbor-helm/values.yaml
(backports #20)
If the init container is run with the DB image and explicit runAsUser: 0
security context, it has several advantages:
- no need to need extra image for init container (busybox in this case)
- possibility to run "chown" command with user:group name instead of UID:GID,
which means the whole DB deployment can work with different database images,
without the need to adapt UID:GID values
Upstream Harbor/1.4.0 PR: https://github.com/goharbor/harbor-helm/pull/685
=> [2.0] Run change-permission-of-directory container with DB image

harbor-helm/templates/_helpers.tpl, harbor-helm/templates/tests/api.yaml, harbor-helm/values.yaml
This change introduces support for running Harbor API tests by using the
helm test command.
The tests are executed in a pod with 2 containers, one for the test
execution itself and the other one running docker daemon. The tests are
the same API tests executed by the Harbor upstream project.
Note: to allow anyone to test this, change the images used for harbor
tests are referencing home/flaviosr. Before merging the test images
needs to be updated with the correct values in the `values.yaml` file.
=> Add support for running API test with helm

harbor-helm/templates/NOTES.txt
Well the question is, what should it point to? Our development repo (like in the commit) or rather public one on kubernetes-charts? Or some documentation page?
=> Update the installation message to not point to upstream repo

harbor-helm/templates/tests/api.yaml
Required when running on kubernetes <= 1.16.
=> Set allowPrivilegeEscalation on test sidecar container

harbor-helm/Chart.yaml, harbor-helm/values-dev.yaml, harbor-helm/values.yaml
Insert tag macros into the Chart.yaml file, to be filled in at
build time by the build service.
Use registry.suse.com as the default registry for image references
in the helm chart and only reference version tags (i.e. without
any revision or build numbers).
Add a values-dev.yaml override that can be used as an additional
helm values file to point to development images coming from
registry.suse.de. This can also be replaced by a build source
service with a registry path corresponding to the build project
where the chart is actually built.
=> Use official image tags and registry paths by default (CAPS-97)

harbor-helm/Chart.yaml, harbor-helm/values-dev.yaml, harbor-helm/values.yaml
(backport of #32 )
Insert tag macros into the Chart.yaml file, to be filled in at
build time by the build service.
Use registry.suse.com as the default registry for image references
in the helm chart and only reference version tags (i.e. without
any revision or build numbers).
Add a values-dev.yaml override that can be used as an additional
helm values file to point to development images coming from
registry.suse.de. This can also be replaced by a build source
service with a registry path corresponding to the build project
where the chart is actually built.
=> [2.0] Use official image tags and registry paths by default (CAPS-97)

harbor-helm/templates/_helpers.tpl
The image scan tests required two image scanners installed to
successfully run. With change [1] merged this is not required anymore so
the scan tests can be enabled whenever trivy is enabled.
1. https://build.suse.de/request/show/225608
=> Enable image scan tests when trivy is enabled

harbor-helm/values-dev.yaml
The entry for the registry controller image is missing on
values-dev.yaml file.
=> Add missing registry/controller image to values-dev

harbor-helm/templates/ingress/ingress.yaml
The nginx-ingress version supplied with CaaSP 4.2 is old and does
not support the newer `backend-protocol` annotation [1]. For older
nginx ingress versions, the `secure-backends` annotation [2] needs
to be used, otherwise the internal TLS support for Harbor doesn't
work.
[1] https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#backend-protocol
[2] https://github.com/kubernetes/ingress-nginx/blob/nginx-0.15.0/docs/user-guide/nginx-configuration/annotations.md#secure-backends
=> [2.0] Fix ingress TLS annotations

harbor-helm/templates/tests/api.yaml
By default the tests expect notary to be served on the 4443 port,
however when using an ingress it is served on 443. This change sets the
`NOTARY_URL` environment variable on the api-tests container with the
value defined on expose.ingress.hosts.notary so the tests are executed
using the correct notary url.
=> Tests: Set NOTARY_URL when using notary with ingress

.github/workflows/cluster-rotate.yml, .github/workflows/periodic-20.yml
This change introduces two workflows for testing SUSE Private Registry
periodically:
* **[CaaSP 4] Rotate Cluster**: This workflow is triggered daily at 4
am and it is responsible for deploying a new CaaSP cluster on ECP,
it also deploys the NGINX ingress controller on the cluster.
To ensure that we always have a cluster available it works by keeping
the `NUMBER_OF_CLUSTERS` deployed and redeploying only the oldest one
until it succeeds.
* **SUSE Private Registry:2.0**: This workflow has one job
(Integration Tests) which is executed every three hours. It is
responsible for testing SUSE Private Registry from devel, suse and
and release areas by deploying it at the last CaaSP cluster deployed
by the `[CaaSP 4] Rotate Cluster` workflow and running the API tests.
=> Add workflows for periodic testing of SUSE Private Registry

harbor-helm/values.yaml
The same variable is already defined at line 449 at `values.yaml`
=> Remove duplicate `registry.serviceAccountName` variable from values

.github/workflows/periodic-20.yml
Since [1] the test image is running robot instead of pybot. Until that
change reaches the SUSE and release channels we need to grep for both
`pybot` and `robot`.
1. https://build.suse.de/request/show/226298
=> Fix run tests CI step for Devel

harbor-helm/values.yaml
(backport of #57)
Add notary to SUSE Private Registry, but keep it disabled by default.
=> [2.0] Add notary to SUSE Private Registry

.github/workflows/periodic-20.yml
The chart directory from the previous run should be deleted as exporting
the chart does not completely overwrites the directory.
=> [2.0] Delete chart pulled on previous run

.github/workflows/periodic-20.yml
The helm chart was updated in 2.0.3 to use `harbor/harbor` as the
registry path instead of `registry/harbor` and to use the `1.4` tag
instead of `latest`, which is a cross-release moving target.
=> Update the 2.0 CI jobs to use the new helm chart tagging scheme

harbor-helm/values.yaml
The values file has `v2.1.0` while the correct tag is `2.1.0`.
=> Fix notary images tag in values file

.github/workflows/periodic-20.yml, .github/workflows/periodic-21.yml
Trivy is running into github rate limiting while downloading the
vulnerability database from https://github.com/aquasecurity/trivy-db.
Using github authentication increases the rate limit from 60 requests
per hour to 5000 requests per hour.
=> CI workflows: use github token for trivy

harbor-helm/templates/tests/api.yaml, harbor-helm/values.yaml
With the tests container also running docker in docker we do not need
another container running docker for the tests anymore.
=> Tests: Remove dependency from docker-dind container

.github/workflows/periodic-21.yml
* Use 1.5 instead of latest as a helm chart tag in the 2.1 CI
* Fix the garbage collection test failures: The integration tests expect the GC window to be set to 0, so that GC jobs have an immediate effect.
=> Fix the GC test failures and use the proper 1.5 tag in the 2.1 CI

.github/workflows/periodic-21.yml
All 2.1 jobs other than the devel job will fail until the changes
are accepted into the SUSE namespace. Disabling these jobs for now.
Also adds a 2.0 to 2.1 (devel) job to periodically test the upgrade.
=> Add 2.0 to devel upgrade job and disable failing 2.1 jobs

.github/workflows/cluster-rotate.yml, .github/workflows/obs-trigger.yml, .github/workflows/registry-2.0.yml, .github/workflows/registry-2.1.yml
A couple more fixes for the registry CI:
* Replace set-env with environment files for the obs trigger and rotate kubernetes cluster workflow (see [1]).
* Fix the cluster prefix when fetching the kubeconfig as it was referencing the previous repository name
* Add notary hostname in the helm values for registry 2.1
1. https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Fixes for the Registry CI

.github/workflows/registry-2.1.yml
The SUSE Private Registry helm chart for 2.1 now defaults to
generating a password for the Harbor admin account. We need the
previous password value to remain the same, otherwise the integration
tests will fail (yes, sadly the default password value is hard-coded
in the integration test code).
=> Use explicit default admin password for 2.1

.github/workflows/cluster-rotate.yml
This allows running more jobs in parallel while not overloading the
cluster.
=> Increase number of CaaSP workers to 6

.github/workflows/cluster-rotate.yml
Installing the logging stack sometimes get a little bit more than 10 minutes.
=> Increse timeout on cluster services install

.github/workflows/cluster-rotate.yml, .github/workflows/registry-2.0.yml
The services namespaces should be deleted after other namespaces or it can leave namespaces stuck on deletion.
This change also fixes the SPR 2.0 workflow by using a label to get the ingress IP instead.
=> Fix ingress IP on SPR 2.0 and namespace deletion

tests/registry/ha+redis-operator/values.yaml
Using a scaled registry with a shared NFS volume is known to not be
stable (see [1]).
1. https://docs.openshift.com/container-platform/3.10/install_config/registry/registry_known_issues.html#known-issue-nfs-image-push-fails
=> Set regitry replicas to 1 on HA+redis-operator

infra/terraform/EKS/modules/postgresql/main.tf, tests/registry/ha+tls+external-db_redis/infra.tfvars
Need to wait until the `aws_rds_cluster_instance` resource is created and the url is resolvable before creating the registry databases.
=> EKS: Wait for DB instance before creating databases
